version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: dshop
      MYSQL_DATABASE: dshop
      MYSQL_USER: dshop
      MYSQL_PASSWORD: dshop
    ports:
      - '3306:3306'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    volumes:
    - "./database:/docker-entrypoint-initdb.d"
  database_test:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: dshop
      MYSQL_DATABASE: dshop_test
      MYSQL_USER: dshop
      MYSQL_PASSWORD: dshop
    ports:
      - '3307:3306'
    volumes:
    - "./database:/docker-entrypoint-initdb.d"
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672
      # volumes:
      #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      networks:
          - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  # db-data:
  database:
    # driver: local
###< doctrine/doctrine-bundle ###
